### ISSUE TITLE
There's a glitch that renders the player unbeatable.

### ISSUE THREAD

**Issue by gezeta-id** [CromulentCoder/Asteroid-Blaster#2]
There's a small glitch that makes it possible for the player to be unbeatable. Not only it breaks the game's fun, it also renders the leader board rather useless -this can be seen in my current record of 30k+ points-. It is related to [this line](https://github.com/CromulentCoder/Asteroid-Blaster/blob/master/public/gamefiles/cannon.js#L12) in `cannon.js`, but fixing it requires a bit more work.

The problem is this:

The `y` position of the cannon is set on that line. This is done when the `Cannon` is instantiated [here](https://github.com/CromulentCoder/Asteroid-Blaster/blob/master/public/gamefiles/sketch.js#L107). The `Cannon`'s `y` position is never modified after that.

Now, if you _resize_ the window, then the `canvas` element is resized too, but the `Cannon` is still left at the original `y` position. And so a player can simply start a game, resize their window to be say `110` pixels less than it was and suddenly, the cannon is _below_ the `canvas`'s lower bound. And then the balls just bounce over, never being able to collide with the cannon.

The solution would be to reset the cannon's `y` position when the window is resized.

_Note that at this moment, there's also a higher, 1000000000 points record. This is unrelated. This is achieved from the browser's console by chaning the appropriate variable/function. But the above issue is unrelated to that and does not involve the console nor messing around with the code in any way._

**Comment by CromulentCoder** [comment]
This should be fixed now. Resetting the position of the cannon every time the window is resized. 
Edit: If you have any tips on how to stop the player from changing the high score variable from the console I'm opening another issue.
