### ISSUE TITLE
Prevent the player from sending false data

### ISSUE THREAD

**Issue by quantumsheep** [CromulentCoder/Asteroid-Blaster#4]
So... yeah... (https://asteroid-blaster.herokuapp.com/game leaderboard)

![image](https://user-images.githubusercontent.com/7271496/54237094-7b7e1100-4515-11e9-9e91-7014c9fdba81.png)

The POST request at `/updateTable` is not secure, just by changing the score's value and the `Content-Length`, I was abble to falsify my highscore and get at the top of the leaderboard.

You need a find a way to secure it. The best way to handle those issues is to make the game not client side managed but server side managed, with asteroids and points managed by the server.

You can't really protect your game by the client's side.

**Comment by CromulentCoder** [comment]
There is already an open issue #3 regarding the same. Please refer to that. I'll make the changes as soon as I find some time for it. Thanks for the concern though.
